server:
  port: 8081
#  servlet:
#    context-path: /acs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acs
    username: root
    password: skillpier123
    driver-class-name: com.mysql.cj.jdbc.Driver
    #com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      com.tingken: debug

  data:
    rest:
      basePath: /acs
